export const STACK_APP = 'STACK_APP'
export const STACK_BUILDS = 'Builds'
export const STACK_ME = 'Me'
export const SCREEN_BUILD_DETAIL = 'SCREEN_BUILD_DETAIL'
export const SCREEN_RAIDER_IO = 'SCREEN_RAIDER_IO'
export const SCREEN_WARCRAFT_LOGS = 'SCREEN_WARCRAFT_LOGS'
